# Generated by Django 5.2.9 on 2025-12-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_alter_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(blank=True, default='new', max_length=20, null=True),
        ),
    ]
